/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaseStudiesSkincareAiVsTraditionalRouteImport } from './routes/case-studies.skincare-ai-vs-traditional'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesSkincareAiVsTraditionalRoute =
  CaseStudiesSkincareAiVsTraditionalRouteImport.update({
    id: '/case-studies/skincare-ai-vs-traditional',
    path: '/case-studies/skincare-ai-vs-traditional',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/case-studies/skincare-ai-vs-traditional': typeof CaseStudiesSkincareAiVsTraditionalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/case-studies/skincare-ai-vs-traditional': typeof CaseStudiesSkincareAiVsTraditionalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/case-studies/skincare-ai-vs-traditional': typeof CaseStudiesSkincareAiVsTraditionalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/case-studies/skincare-ai-vs-traditional'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/case-studies/skincare-ai-vs-traditional'
  id: '__root__' | '/' | '/case-studies/skincare-ai-vs-traditional'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaseStudiesSkincareAiVsTraditionalRoute: typeof CaseStudiesSkincareAiVsTraditionalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/skincare-ai-vs-traditional': {
      id: '/case-studies/skincare-ai-vs-traditional'
      path: '/case-studies/skincare-ai-vs-traditional'
      fullPath: '/case-studies/skincare-ai-vs-traditional'
      preLoaderRoute: typeof CaseStudiesSkincareAiVsTraditionalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaseStudiesSkincareAiVsTraditionalRoute:
    CaseStudiesSkincareAiVsTraditionalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
